//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAWcod.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercitii
    {
        public exercitii()
        {
            this.utilizatori_exercitii = new HashSet<utilizatori_exercitii>();
        }
    
        public System.Guid id_exercitiu { get; set; }
        public string nume_exercitiu { get; set; }
        public string descriere { get; set; }
    
        public virtual ICollection<utilizatori_exercitii> utilizatori_exercitii { get; set; }
    }
}
