//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAWcod.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class goal
    {
        public goal()
        {
            this.utilizatoris = new HashSet<utilizatori>();
        }
    
        public System.Guid id_goal { get; set; }
        public string tip_corp { get; set; }
        public string descriere { get; set; }
    
        public virtual ICollection<utilizatori> utilizatoris { get; set; }
    }
}
