//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAWcod.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProiectDAWEntities : DbContext
    {
        public ProiectDAWEntities()
            : base("name=ProiectDAWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<contact> contacts { get; set; }
        public DbSet<exercitii> exercitiis { get; set; }
        public DbSet<goal> goals { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<utilizatori> utilizatoris { get; set; }
        public DbSet<utilizatori_exercitii> utilizatori_exercitii { get; set; }
    }
}
