//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAWcod.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilizatori_exercitii
    {
        public System.Guid id_utilizatori_exercitii { get; set; }
        public System.Guid id_utilizator { get; set; }
        public System.Guid id_exercitiu { get; set; }
    
        public virtual exercitii exercitii { get; set; }
        public virtual utilizatori utilizatori { get; set; }
    }
}
