//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProiectDAWcod.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilizatori
    {
        public utilizatori()
        {
            this.utilizatori_exercitii = new HashSet<utilizatori_exercitii>();
        }
    
        public System.Guid id_utilizator { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public System.Guid id_goal { get; set; }
        public System.Guid id_contact { get; set; }
    
        public virtual contact contact { get; set; }
        public virtual goal goal { get; set; }
        public virtual ICollection<utilizatori_exercitii> utilizatori_exercitii { get; set; }
    }
}
